export { default as GetTestMail } from './lib/client'
export { GetTestMail as Mailbox } from './lib/models'
export { APIError } from './lib/models'
export { Problem } from './lib/models'
export { Message } from './lib/models'
export { Attachment } from './lib/models'